### ISSUE TITLE
EventStoreStatusPublisher concurrency

### ISSUE THREAD

**Issue by jgeraerts** [OasisDigital/nges#2]
I was reading some of this code, and was wondering if there shouldn't be some synchronization primitives in place to protect from raceconditions around the `lastEventId` variable.

**Comment by kylecordes** [comment]
Looking back at this code, I don't have confidence about how the instances of this class are managed, whether it is possible for there to be a race with two different threads calling publishLastEventIfChanged on the same instance.  I will ask the guru who wrote this bit of code to join us here and take a look. My guess is that ```publishLastEventIfChanged``` should be ```synchronized```.

**Comment by konrad-garus** [comment]
If you're thinking about `EventStoreStatusPublisher`, then from a very quick look I think you are correct. Offhand it seems like it should be using something like `AtomicLong` or synchronization. Even if it was correctly serialized 100% of the time on the publisher, it doesn't guarantee ordering of delivery over the network.

This library has been extracted from a larger project which took a single-writer approach (basically a single-threaded command gateway). This explains why it worked without problems there, but on its own it does seem to have this race condition.

**Comment by kylecordes** [comment]
Looking at the code, a comment at the top of this file, I think the problem exists here regardless of whether it happens to be used in a single writer manner. The comment points out that there could be a race condition between even a single writing thread, plus the background heartbeat thread. Therefore I believe the message should be synchronized (a single word change) to fix the problem regardless of the context.

I adore test driven development, but at this moment I have sufficient motivation for the one word fix but not sufficient motivation to build out a test case which reveals this particular race. So I'll put the fix in shortly.

Notably, this concurrency bug would not affect the correctness of the system, but only make it slightly less live (the wake up into mechanism could miss), which the design already tolerates anyway. So it's unlikely a real application whatever actually have had visibly incorrect results. This is of course my favorite kind of bug..  yet it still warrants a fix shortly.

**Comment by kylecordes** [comment]
This is fixed in https://github.com/OasisDigital/nges/commit/8843680bc524c8476eb648d368a0a6ce7c1a8a00
